openapi: 3.0.0
info:
  description: "API template"
  version: "0.0.0"
  title: "API template"
servers:
  - url: 'http://localhost:3000/'
paths:
  /flights:
    get:
      tags:
        - "flights"
      summary: "It should send a list of flights"
      parameters:
        - in: query
          name: departure
          schema:
            type: string
          description: The number of items to skip before starting to collect the result set
        - in: query
          name: arrival
          schema:
            type: integer
          description: The numbers of items to return
    post:
      tags:
        - "flights"
      summary: "It should create a flight"
  /flights/{flightNumber}:
    get:
      tags:
        - "flights"
      summary: "It should return the seleted flight"
      parameters:
        - name: flightNumber
          in: path
          required: true
          description: Enter a number.
          schema:
            type : integer
            format: int64
            minimum: 1
    put:
      tags:
        - "flights"
      summary: "It should update the seleted flight"
      parameters:
        - name: flightNumber
          in: path
          required: true
          description: Enter a number.
          schema:
            type : integer
            format: int64
            minimum: 1
    delete:
      tags:
        - "flights"
      summary: "It should update the seleted flight"
      parameters:
        - name: flightNumber
          in: path
          required: true
          description: Enter a number.
          schema:
            type : integer
            format: int64
            minimum: 1